project:
  type: website
  output-dir: docs

website:
  title: "pmsims"
  navbar:
    search: false
    collapse: true
    background: primary
    pinned: true
    left:
      - href: index.qmd#about
        text: About
      - href: team.qmd
        text: Team
      - href: index.qmd#contact
        text: Contact
      - href: news.qmd
        text: News
    right:
      - href: https://pmsims-package.github.io/pmsims/
        text: R package
    tools:
      - icon: github
        href: https://github.com/pmsims-package/pmsims
        text: GitHub

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    markdown:
      extensions: [fenced-divs]
