project:
  type: website
  output-dir: _site

website:
  title: "Home"
  navbar:
    search: false
    collapse: true
    background: primary
    pinned: true
    left:
      - href: index.qmd#about
        text: About
      - href: team.qmd
        text: Team
      - href: index.qmd#contact
        text: Contact
      - href: news.qmd
        text: News

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    include-after-body: templates/navbar-mobile-news.html
    toc: true
    markdown:
      extensions: [fenced-divs]
